Add support for M2tsVideo in ClicsModel
icpc/live-v3 pull request #155
Opened 2024-03-10 03:59 UTC by cubercsl

This is out patch used in [The 2023 ICPC Asia East Continent Final Contest](https://icpc.global/regionals/finder/Shanghai-2024). 

But it is based on v3.1.1. Maybe should rebase to the latest version.

[Live Stream](https://www.bilibili.com/video/BV1RT4y1n7w1/)

2024-03-10 19:18 UTC, kunyavskiy commented on src/cds-converter/src/main/kotlin/org/icpclive/export/clics/ClicsExporter.kt
> +    is MediaType.M2tsVideo -> Media("video", url)
Shouldn't it be video/m2ts for consistency with parser?

2024-03-10 19:19 UTC, kunyavskiy commented on src/cds/core/src/main/kotlin/org/icpclive/cds/adapters/AdvancedPropertiesAdapter.kt
> +    is MediaType.M2tsVideo -> copy(url = url.applyTemplate(valueProvider))
It should be also urlEncoded.

2024-03-10 19:20 UTC, kunyavskiy requested changes
Backend changes sounds good to me, except two minor comments above.

2024-03-11 12:27 UTC, cubercsl commented
`advanced.schema.json` need be updated

2024-03-11 12:50 UTC, cubercsl commented
Maybe this change is similar to #148 except for the video type. AFAIK, the latest cds support both video type.

2024-03-11 12:59 UTC, kunyavskiy commented
> `advanced.schema.json` need be updated

You can do it with `./gradlew gen` and committing corresponding changes.

2024-03-11 13:09 UTC, cubercsl commented on src/frontend/overlay/src/components/organisms/holder/ContestantViewHolder.tsx
> +            });
According to [this](https://github.com/xqq/mpegts.js/blob/master/docs/api.md#config), request header for video's auth can be added by config here.

2024-03-11 14:59 UTC, kbats183 approved these changes

2024-03-13 19:45 UTC, kbats183 approved these changes

2024-03-13 20:04 UTC, merged