Add buttons to titles
icpc/live-v3 pull request #172
Opened 2024-04-09 14:41 UTC by fallnlove

2024-04-09 14:53 UTC, Mond1c requested changes

2024-04-09 14:53 UTC, Mond1c commented on src/frontend/admin/src/components/Title.js
> +                    data.settings.preset = "title_left.svg";
Hard code

2024-04-09 14:53 UTC, Mond1c commented on src/frontend/admin/src/components/Title.js
> +                    data.settings.preset = "title_right.svg";
Hard code

2024-04-09 14:53 UTC, irdkwmnsb commented on src/frontend/admin/src/components/Title.js
> +                    data.settings.preset = "title_left.svg";
Hardcoded value. This preset needs to be able to change. It's good for what it's worth. But maybe we can add some sort of logic or interface to be able to add more such buttons, or less of such buttons?

2024-04-10 19:01 UTC, irdkwmnsb commented on src/frontend/admin/src/components/Title.js
> +                    data.settings.preset = "title_left.svg";
React doesn't like when props are mutated. Here you are mutating `data`. This is prone to bugs

2024-04-21 09:24 UTC, closed without merging

2024-04-21 23:13 UTC, irdkwmnsb commented
Closed in favour of #175