Rewrite widget logic: WidgetControllers
icpc/live-v3 pull request #60
Opened 2022-08-03 11:33 UTC by kbats183

All the logic of working with widgets has been moved to `widget` package. For widget managment has been created PresetsController (for widgets with presets) and SimpleController (for other widgets).
Admin widget routing are configured in the `admin.Widget`.

2022-08-04 19:33 UTC, azat-ismagilov requested changes

2022-08-04 19:33 UTC, azat-ismagilov commented on backend/src/main/kotlin/org/icpclive/admin/Routing.kt
> +                    val mediaDirectoryFile = Config.mediaDirectory.toFile()
Давай эту функцию вынесем в другой файл, как /regions?

2022-08-04 19:33 UTC, azat-ismagilov commented on backend/src/main/kotlin/org/icpclive/admin/Widgets.kt
> +package org.icpclive.admin
Почему setupController это не метод класса controller?

2022-08-04 19:33 UTC, azat-ismagilov commented on backend/src/main/kotlin/org/icpclive/cds/clics/api/Objects.kt
> +    val group_ids: List<String> = emptyList(),
Пожалуйста, давай не смешивать в одном ревью изменения кодстайла и изменения логики. Предлагаю отсюда удалить, сделать отдельно.

2022-08-04 19:33 UTC, azat-ismagilov commented on backend/src/main/kotlin/org/icpclive/cds/clics/ClicsDataSource.kt
> -                        logger.info(it.data.toString())
Почему изменения cds в этом ревью?

2022-08-04 19:33 UTC, azat-ismagilov commented on backend/src/main/kotlin/org/icpclive/api/Objects.kt
> +data class ObjectStatus<SettingsType : ObjectSettings>(
Давай это тоже уберём, тоже не относится к изменениям виджетов

2022-08-04 19:33 UTC, azat-ismagilov commented on backend/src/main/kotlin/org/icpclive/widget/PresetsController.kt
> +    override suspend fun getStatus(): ObjectStatus<SettingsType> = mutex.withLock {
Что-то какая-то мутная логика конечно. Добавь TODO refactor, я однажды посмотрю.

2022-08-04 19:35 UTC, kbats183 commented on backend/src/main/kotlin/org/icpclive/cds/clics/api/Objects.kt
> +    val group_ids: List<String> = emptyList(),
оно случайно попало и не хочется откатывать

2022-08-04 19:39 UTC, azat-ismagilov commented on backend/src/main/kotlin/org/icpclive/cds/clics/api/Objects.kt
> +    val group_ids: List<String> = emptyList(),
> оно случайно попало и не хочется откатывать
Надо, надо
В смысле это потом сильно снизит читаемость коммитов

2022-08-04 20:09 UTC, kbats183 commented on backend/src/main/kotlin/org/icpclive/api/Objects.kt
> +data class ObjectStatus<SettingsType : ObjectSettings>(
No, this change is important because widget may potentially not have the status. I used it

2022-08-05 06:28 UTC, kunyavskiy commented on backend/src/main/kotlin/org/icpclive/Config.kt
> +    fun initialize(environment: ApplicationEnvironment) {
To be honest, loocks a bit overloaded now. Maybe just have 

lateinit var Config and normal constructor?

2022-08-05 06:28 UTC, kunyavskiy commented on backend/src/main/kotlin/org/icpclive/widget/WidgetWrapper.kt
> +    suspend fun getWidget() = mutex.withLock {
Still really don't like this function name

2022-08-05 06:28 UTC, kunyavskiy commented on backend/src/main/kotlin/org/icpclive/admin/Action.kt
> +suspend inline fun <T> ApplicationCall.safeReceive(serializer: KSerializer<T>): T = try {
I didn't understand well how we was able not to use this function directly, but if we can, we don't need this serializer stuff, and can user receive, not receiveText.

2022-08-14 19:01 UTC, azat-ismagilov approved these changes

2022-08-15 19:10 UTC, kunyavskiy approved these changes

2022-08-16 07:11 UTC, merged